[project]
name = "nbastatsapp"
version = "1.0.0"
description = "NBA Stats App to visualize NBA stats"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["polars>=1.22.0", "streamlit >=1.42.0", "plotly>=6.0.0", "psycopg2-binary>=2.9.9", "statsmodels>=0.14.4"]
